// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nufcohuczrofcntdjzkn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51ZmNvaHVjenJvZmNudGRqemtuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyOTU2NjQsImV4cCI6MjA1OTg3MTY2NH0.g6owK4nkMCIg2KaLd1qEVMsu6qQyqOdlEr1Hpqtqejo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);